radio.setGroup(25)
basic.forever(function () {
    music.playTone(131, music.beat(BeatFraction.Whole))
    radio.sendNumber(input.temperature())
    basic.pause(2000)
    basic.showNumber(input.temperature())
    radio.sendNumber(input.lightLevel())
    basic.showNumber(input.lightLevel())
    basic.pause(2000)
    radio.sendNumber(input.soundLevel())
    basic.showNumber(input.soundLevel())
    basic.pause(2000)
    music.playTone(988, music.beat(BeatFraction.Whole))
})
